#!/bin/sh

fslist="proc sys dev run"
rodir=run/initramfs/ro
rwdir=run/initramfs/rw
upper=$rwdir/cow
work=$rwdir/work
mmcdir=/mnt

cd /
# shellcheck disable=SC2086
mkdir -p $fslist
mount dev dev -tdevtmpfs
mount sys sys -tsysfs
mount proc proc -tproc
mount tmpfs run -t tmpfs -o mode=755,nodev

mkdir -p $rodir $rwdir $mmcdir

cp -rvp init shutdown update whitelist bin sbin usr lib etc var run/initramfs

rofst=squashfs
roopts=ro
rwopts=rw

image=/run/initramfs/image-
trigger=${image}rwfs

init=/sbin/init
fsckopts=-a
update=/run/initramfs/update

echo "mounting MMC"
/usr/bin/tftp -g -l /run/rootfs.squashfs -r rootfs.squashfs 192.168.70.254
mount -t squashfs /run/rootfs.squashfs $rodir
mkdir -p $upper $work /root

echo "mounting OVERLAYFS"
mount -t overlay -o lowerdir=$rodir,upperdir=$upper,workdir=$work cow /root

for f in $fslist
do
	mount --move $f root/$f
done
exec switch_root /root $init
#exec /bin/sh

